services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 2345:5432
    env_file:
      - ./back-end/.env.test
  node_app:
    build: ./back-end
    container_name: node_app
    ports:
      - 5000:5000
    depends_on:
      - postgres_db
    env_file:
      - ./back-end/.env.test

